Models/ApplicationDBContext.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CrudRazor.Models
{
    public class ApplicationDBContext : DbContext
    {

        public ApplicationDBContext(DbContextOptions<ApplicationDBContext> options) : base (options)
        {

        }

        public DbSet<Curso> cursos { get; set; }

    }
}

Models/Curso.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CrudRazor.Models
{
    public class Curso
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [Display(Name ="Nombre de Curso")]
        public string NombreCurso { get; set; }
        [Display(Name = "Cantidad de Clases")]
        public int CantClases { get; set; }
        public int Precio { get; set; }

    }
}

Pages/Curso/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using CrudRazor.Models;
namespace CrudRazor.Pages.Curso
{
    public class CreateModel : PageModel
    {

        private readonly ApplicationDBContext _db;
        public CreateModel(ApplicationDBContext db)
        {
            _db = db;
        }

        [BindProperty]
        public CrudRazor.Models.Curso Curso { get; set; }
        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPost() 
        {
            if (!ModelState.IsValid)
                return Page();

            _db.Add(Curso);
            await _db.SaveChangesAsync();

            return RedirectToPage("Index");
        }
    }
}

Pages/Curso/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CrudRazor.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CrudRazor.Pages.Curso
{
    public class EditModel : PageModel
    {
        private readonly ApplicationDBContext _db;

        public EditModel(ApplicationDBContext db)
        {
            _db = db;
        }

        [BindProperty]
        public CrudRazor.Models.Curso Curso { get; set; }

        public async Task OnGet(int id)
        {
            Curso = await _db.cursos.FindAsync(id);
        }

        public async Task<IActionResult> OnPost()
        {
            if (!ModelState.IsValid)
                return Page();

            var cursoObtenido = await _db.cursos.FindAsync(Curso.Id);
            cursoObtenido.NombreCurso = Curso.NombreCurso;
            cursoObtenido.CantClases = Curso.CantClases;
            cursoObtenido.Precio = Curso.Precio;

            await _db.SaveChangesAsync();

            return RedirectToPage("Index");
        }
    }
}

Pages/Curso/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CrudRazor.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace CrudRazor.Pages.Curso
{
    public class IndexModel : PageModel
    {

        private readonly ApplicationDBContext _db;
        public IndexModel(ApplicationDBContext db) {
            _db = db;
        }

        public IEnumerable<CrudRazor.Models.Curso> Cursos { get; set; }

        public async  Task OnGet()
        {
            Cursos = await _db.cursos.ToListAsync();
             
        }

        public async Task<IActionResult> OnPostDelete(int id)
        {
            var curso = await _db.cursos.FindAsync(id);
            if (curso == null) 
                return NotFound();

            _db.cursos.Remove(curso);
            await _db.SaveChangesAsync();

            return RedirectToPage("Index");
        }
    }
}

Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace CrudRazor.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CrudRazor.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CrudRazor.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Pages/Curso/Create.cshtml
@page
@model CrudRazor.Pages.Curso.CreateModel
@{
    ViewData["Title"] = "Crear Curso"; 
}
<br />
<h2 class="text-info">Crear Nuevo Curso</h2>
<div class="border">
    <form method="post">
       <div asp-validation-summary="ModelOnly" class="text-danger" ></div>
       <div class="container" style="padding:30px">
           <div class="form-group">
               <div class="row">
                   <div class="col-sm-2">
                       <label asp-for="Curso.NombreCurso"></label>
                   </div>
                   <div class="col-sm-4">
                       <input asp-for="Curso.NombreCurso" class="form-control" />
                   </div>
                   <span asp-validation-for="Curso.NombreCurso" class="text-danger"></span>
               </div>
           </div>
           <div class="form-group">
               <div class="row">
                   <div class="col-sm-2">
                       <label asp-for="Curso.CantClases"></label>
                   </div>
                   <div class="col-sm-4">
                       <input asp-for="Curso.CantClases" class="form-control" />
                   </div>
                   <span asp-validation-for="Curso.CantClases" class="text-danger"></span>
               </div>
           </div>
           <div class="form-group">
               <div class="row">
                   <div class="col-sm-2">
                       <label asp-for="Curso.Precio"></label>
                   </div>
                   <div class="col-sm-4">
                       <input asp-for="Curso.Precio" class="form-control" />
                   </div>
                   <span asp-validation-for="Curso.Precio" class="text-danger"></span>
               </div>
           </div>
           <div class="form-group">
               <div class="row">
                   <div class="col-sm-2 offset-sm-2">
                       <input type="submit" value="Crear" class="btn  btn-primary form-control" />
                   </div>
                   <div class="col-sm-2">
                       <a asp-page="Index"  class="btn btn-warning">Regresar</a>
                   </div>
               </div>
           </div>
       </div>
    </form>
</div>

Pages/Curso/Edit.cshtml
@page
@model CrudRazor.Pages.Curso.EditModel
@{
}
<br />
<h2 class="text-info">Editar Nuevo Curso</h2>
<div class="border">
    <form method="post">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden"  asp-for="Curso.Id"/>
        <div class="container" style="padding:30px">
            <div class="form-group">
                <div class="row">
                    <div class="col-sm-2">
                        <label asp-for="Curso.NombreCurso"></label>
                    </div>
                    <div class="col-sm-4">
                        <input asp-for="Curso.NombreCurso" class="form-control" />
                    </div>
                    <span asp-validation-for="Curso.NombreCurso" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-sm-2">
                        <label asp-for="Curso.CantClases"></label>
                    </div>
                    <div class="col-sm-4">
                        <input asp-for="Curso.CantClases" class="form-control" />
                    </div>
                    <span asp-validation-for="Curso.CantClases" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-sm-2">
                        <label asp-for="Curso.Precio"></label>
                    </div>
                    <div class="col-sm-4">
                        <input asp-for="Curso.Precio" class="form-control" />
                    </div>
                    <span asp-validation-for="Curso.Precio" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-sm-2 offset-sm-2">
                        <input type="submit" value="Editar" class="btn  btn-primary form-control" />
                    </div>
                    <div class="col-sm-2">
                        <a asp-page="Index" class="btn btn-warning">Regresar</a>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>

Pages/Curso/Index.cshtml
@page
@model CrudRazor.Pages.Curso.IndexModel
@{
    ViewData["Title"] = "Index";
}
<br />
<div class="container row">
    <div class="col-6">
        <h2 class="text-info">Listado de Cursos</h2>
    </div>
    <div class="col-6 text-right">
        <a asp-page="Create" class="btn btn-primary">Crear Nuevo Curso</a>
    </div>
</div>
<form method="post">
    @if (Model.Cursos.Count() > 0)
    {
        <br />
        <table class="table table-striped border">
            <tr class="table-secondary">
                <th>Nombre del Curso</th>
                <th>Cant. Clases </th>
                <th>Precio </th>
                <th>Acciones</th>
            </tr>
            @foreach (var item in Model.Cursos)
            {
                <tr>
                    <td>@item.NombreCurso</td>
                    <td>@item.CantClases</td>
                    <td>@item.Precio</td>
                    <td>
                        <button asp-page-handler="Delete" asp-route-id="@item.Id" onclick="return confirm('Esta seguro de querer borrar el curso')" class="btn  btn-danger btn-sm">Borrar</button>
                        <a asp-route-id="@item.Id" asp-page="Edit" class="btn btn-success btn-sm">Editar</a>

                    </td>

                </tr>

            }

        </table>
    }
    else
    {
        <p>No Hay registros</p>
    }
</form>

Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CrudRazor</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">CrudRazor</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-page="Curso/Index">Cursos</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - CrudRazor - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>